// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5LR5zfSrdyFqZ9KxnU2Ng92661NfGN0Q',
    appId: '1:1098186330380:web:b8c53e7b90d402b6bc7929',
    messagingSenderId: '1098186330380',
    projectId: 'flutter-822a9',
    authDomain: 'flutter-822a9.firebaseapp.com',
    storageBucket: 'flutter-822a9.firebasestorage.app',
    measurementId: 'G-XW7CDSKTTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdLtYPGpkCvZMmeMf--8Etw2Nnij-6RjM',
    appId: '1:1098186330380:android:81dcbc650eddf1d9bc7929',
    messagingSenderId: '1098186330380',
    projectId: 'flutter-822a9',
    storageBucket: 'flutter-822a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbgrf-kzSHrtqdoVkUAEpO0GkxrrJrhpg',
    appId: '1:1098186330380:ios:d2179c6ce7e9247abc7929',
    messagingSenderId: '1098186330380',
    projectId: 'flutter-822a9',
    storageBucket: 'flutter-822a9.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbgrf-kzSHrtqdoVkUAEpO0GkxrrJrhpg',
    appId: '1:1098186330380:ios:d2179c6ce7e9247abc7929',
    messagingSenderId: '1098186330380',
    projectId: 'flutter-822a9',
    storageBucket: 'flutter-822a9.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5LR5zfSrdyFqZ9KxnU2Ng92661NfGN0Q',
    appId: '1:1098186330380:web:8464d4cc8f1309f7bc7929',
    messagingSenderId: '1098186330380',
    projectId: 'flutter-822a9',
    authDomain: 'flutter-822a9.firebaseapp.com',
    storageBucket: 'flutter-822a9.firebasestorage.app',
    measurementId: 'G-6HEEWNX9G5',
  );

}