import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by Firebase CLI
import 'survey_page.dart';
import 'results_page.dart';
import 'login_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Survey App',
      theme: ThemeData(primarySwatch: Colors.blue),
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginPage(),
        '/survey': (context) => const SurveyPage(),
        '/results': (context) {
          final args = ModalRoute.of(context)!.settings.arguments
              as List<Map<String, dynamic>>;
          return ResultsPage(answers: args);
        },
      },
      debugShowCheckedModeBanner: false,
    );
  }
}
