name: questionnaire
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.8
  google_sign_in: ^6.2.2

  # Mise à jour des dépendances
  async: ^2.11.0
  boolean_selector: ^2.1.1
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  fake_async: ^1.3.1
  http_parser: ^4.0.2
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  matcher: ^0.12.16+1
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  vm_service: ^14.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
